name: CD staging

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: appleboy/ssh-action@master
        name: executing remote ssh commands using password
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script_stop: true
          script: |
            cd /home/clients/0595bb847356d02f4b5bca65b97759a6/sites/blink.dotmind.io/blink
            git checkout develop
            git pull origin develop
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 16
            npm i
            npm run build
